kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-1
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/postgresql-anchore"
    type: DirectoryOrCreate

